# Generated by Django 6.0.5 on 2026-06-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artwork', models.ImageField(upload_to='tracks/artwork/')),
                ('preview', models.FileField(upload_to='tracks/previews/')),
                ('description', models.TextField()),
                ('spotify_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
