# Generated by Django 6.0.5 on 2026-06-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='homepage_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='record_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='track',
            name='record_label_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='track',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
