# Generated by Django 6.0.5 on 2026-06-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_track_homepage_order_track_record_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='tag_exclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='tag_teaser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='tag_unreleased',
            field=models.BooleanField(default=False),
        ),
    ]
